### ISSUE TITLE
Multiple stack exchange sites

### ISSUE THREAD

**Issue by dimateos** [Sammy-T/dewy#12]
Hey! first of all, really cool concept. I was wondering if you could extend this to wrap all stack exchange sites. For example it would be cool to be able to search among:
* stackoverflow
* [serverfault](https://serverfault.com/)
* [gamedev](https://gamedev.stackexchange.com/)
* [blender](https://blender.stackexchange.com/)
* etc

If you go to [network profile](https://stackexchange.com/users/20968655/dimateos?tab=accounts) you can see all the stack sites a user has accounts in.

Or directly in the [bookmarks tab](https://stackexchange.com/users/20968655/dimateos?tab=bookmarks) you can see the bookmarks from all the sites combined.

> I think this could add a lot of value

**Comment by Sammy-T** [comment]
That's a good suggestion. When I have the time, I'll take a look into that.

**Comment by Sammy-T** [comment]
I've added a dropdown to select the site to search. I'm considering adding an 'all sites' option in the future but I'm not sure right now as that would most likely be a more involved process.
